modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"

[[mods]]
modId="oreo_mod"
version="1.0"
displayName="OrangeOreoMod"
displayURL="https://github.com/Soakuma"
credits="pinne[ @dev_pinne_ ]\n     오렌지 오레오 [ @wallpaper40502 ]"
authors="pinne"
description="오렌지오레오님 리퀘"

[[dependencies.oreo_mod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"




